/* ─── Landing page data ─── */

export const FEATURES = [
  { tag: 'AUTO-RECOVERY',   name: 'Stream Goes Down — Tally Fixes It',       desc: 'Auto-recovery restarts your stream before the congregation even notices. Works with OBS, vMix, and hardware encoders.' },
  { tag: 'ALERTS',          name: 'Slack + Telegram Alerts',                 desc: 'Your TD gets an alert on Slack or Telegram in seconds — with diagnosis steps and one-tap acknowledge. Escalation if nobody responds in 90 seconds.' },
  { tag: 'PRE-SERVICE',     name: 'Automated System Check',                  desc: 'Green-light confirmation 30 min before every service. Every device tested, every connection verified. No more manual walkthroughs.' },
  { tag: 'REMOTE CONTROL',  name: 'Deep ProPresenter + ATEM Control',        desc: 'Cut cameras, advance slides, trigger looks, send stage messages, start timers — all from your phone or Telegram.' },
  { tag: 'AI COMMANDS',     name: 'Natural Language Control',                desc: 'Type "cut to camera 2 then start recording" and Tally does it. AI-powered command parsing understands plain English — no menus needed.' },
  { tag: 'AUTOPILOT',       name: 'AI Autopilot',                            desc: 'Create rules like "when worship slides start, switch to cam 1." Tally executes automatically during service — up to 25 rules on Enterprise.' },
  { tag: 'CHURCH PORTAL',   name: 'Self-Service Church Portal',              desc: 'Every church gets their own dashboard — manage TDs, set service schedules, view session history, configure alerts, and handle billing.' },
  { tag: 'TIMELINE',        name: 'Post-Service Debrief',                    desc: 'Every service gets a timeline: what happened, what broke, what auto-recovered. Session recaps push into Planning Center automatically.' },
  { tag: 'PLANNING CENTER', name: 'Planning Center Sync + Write-Back',       desc: 'Pull service times automatically. After each service, production notes push back into the plan — no manual data entry.' },
  { tag: 'GUEST ACCESS',    name: 'Guest TD Tokens',                         desc: 'Generate temporary access tokens for guest TDs or volunteers. Auto-expire in 7 days. Full audit trail of every action.' },
  { tag: 'ON-CALL',         name: 'On-Call TD Rotation',                     desc: 'Weekly rotation with Telegram swap commands. Alerts route to whoever is on-call — not everyone on the team.' },
  { tag: 'REPORTING',       name: 'Monthly Health Reports',                  desc: 'Uptime stats, incidents, and auto-recoveries per church. Monthly health reports keep leadership in the loop — delivered on the 1st of every month.' },
  { tag: 'AI SETUP',        name: 'AI Setup Assistant',                      desc: 'Upload a patch list or camera plot and Tally auto-configures your mixer channels and ATEM input labels. Parses CSVs, PDFs, and photos using AI vision — setup in minutes, not hours.' },
  { tag: 'MULTI-SITE',      name: 'Built For Multi-Room',                    desc: 'Start with one room on Connect, scale to 3 on Plus, 5 on Pro, or unlimited on Enterprise — without adding chaos to Sunday.' },
  { tag: 'MULTI-ENCODER',   name: 'Any Encoder, Any Workflow',               desc: 'OBS, vMix, Ecamm, Blackmagic, Teradek, YoloBox, Epiphan, AJA HELO — Tally monitors whatever encoder you run.' },
  { tag: 'LIVE PREVIEW',    name: 'Live Video Preview',                      desc: 'See your program feed from anywhere. H.264 monitoring stream routed securely — watch your production in real time from your phone.' },
  { tag: 'SETUP GUIDES',    name: '15 Step-by-Step How-To Guides',           desc: 'Plain-language setup guides with Quick Start summaries, difficulty ratings, and collapsible advanced details. Written for volunteers, not engineers.' },
];

export const INTEGRATIONS = [
  { name: 'ATEM Switcher',       tag: 'SWITCHER'  },
  { name: 'OBS Studio',          tag: 'STREAMING' },
  { name: 'vMix',                tag: 'STREAMING' },
  { name: 'Ecamm Live',          tag: 'STREAMING' },
  { name: 'ProPresenter',        tag: 'SLIDES'    },
  { name: 'Bitfocus Companion',  tag: 'CONTROL'   },
  { name: 'Planning Center',     tag: 'SCHEDULE'  },
  { name: 'Slack',               tag: 'ALERTS'    },
  { name: 'Telegram',            tag: 'ALERTS'    },
  { name: 'Resolume Arena',      tag: 'VIDEO WALL'},
  { name: 'Allen & Heath',       tag: 'AUDIO'     },
  { name: 'Behringer X32',       tag: 'AUDIO'     },
  { name: 'Midas M32',           tag: 'AUDIO'     },
  { name: 'Yamaha CL/QL',        tag: 'AUDIO'     },
  { name: 'Dante Audio',         tag: 'AUDIO'     },
  { name: 'HyperDeck',           tag: 'RECORD'    },
  { name: 'PTZ Cameras',         tag: 'CAMERA'    },
  { name: 'Video Hub',           tag: 'ROUTER'    },
  { name: 'Blackmagic Encoder',  tag: 'ENCODER'   },
  { name: 'Teradek',             tag: 'ENCODER'   },
  { name: 'YoloBox',             tag: 'ENCODER'   },
  { name: 'Epiphan',             tag: 'ENCODER'   },
  { name: 'AJA HELO',            tag: 'ENCODER'   },
];

export const STEPS = [
  {
    num: '01',
    title: 'Install',
    desc: '10-minute setup. Run the app on your booth computer. It auto-discovers your ATEM, OBS, and Companion. The AI Setup Assistant can auto-configure your mixer and camera labels from a patch list.',
  },
  {
    num: '02',
    title: 'Connect',
    desc: 'Your church appears live on the Tally dashboard. Every device, every status — instantly visible from anywhere.',
  },
  {
    num: '03',
    title: 'Relax',
    desc: 'Tally watches your entire production. If something breaks, it fixes it first — then tells you.',
  },
];

export const PRICING = [
  {
    name: 'Connect',
    plan: 'connect',
    monthlyPrice: 49,
    annualPrice: 490,
    desc: 'Monitoring, alerts, and remote control for a single room.',
    featured: false,
    cta: 'Start Free Trial \u2192',
    ctaHref: '/signup?plan=connect',
    features: [
      '1 room included',
      'ATEM, OBS, vMix monitoring',
      'Pre-service automated check',
      'Slack + Telegram alerts with escalation',
      'Telegram remote control',
      'Auto-recovery (stream restart)',
      'Post-service incident timeline',
      'Church Portal (self-service dashboard)',
      'Email support',
    ],
  },
  {
    name: 'Plus',
    plan: 'plus',
    monthlyPrice: 99,
    annualPrice: 990,
    desc: 'Full integrations, live preview, and multi-room support for growing teams.',
    featured: false,
    cta: 'Start Free Trial \u2192',
    ctaHref: '/signup?plan=plus',
    features: [
      'Everything in Connect',
      'Up to 3 rooms',
      'All 23 device integrations',
      'Deep ProPresenter control (looks, timers, stage messages)',
      'Live video preview stream',
      'On-call TD rotation',
      'Guest TD access tokens',
      'AI natural language commands',
      'AI Setup Assistant (auto-configure from patch lists)',
      'Priority email support',
    ],
  },
  {
    name: 'Pro',
    plan: 'pro',
    monthlyPrice: 149,
    annualPrice: 1490,
    desc: 'AI autopilot, Planning Center sync, and monthly reports for multi-room operations.',
    featured: true,
    cta: 'Start Free Trial \u2192',
    ctaHref: '/signup?plan=pro',
    features: [
      'Everything in Plus',
      'Up to 5 rooms',
      'AI Autopilot (10 automation rules)',
      'Planning Center sync + production write-back',
      'Monthly health reports for leadership',
      'Session recaps with full timeline',
      'Priority support',
    ],
  },
  {
    name: 'Enterprise',
    plan: 'managed',
    monthlyPrice: 499,
    annualPrice: 4990,
    desc: 'Unlimited rooms, white-glove onboarding, and dedicated support.',
    featured: false,
    cta: 'Contact Sales \u2192',
    ctaHref: 'mailto:sales@atemschool.com',
    features: [
      'Everything in Pro',
      'Unlimited rooms',
      'Dedicated onboarding & configuration',
      'AI Autopilot (25 automation rules)',
      'Custom autopilot rules built for you',
      'Remote configuration changes',
      'Monthly system health review',
      '15-minute response SLA (Mon–Fri 9–5 ET + service windows)',
      'Dedicated support engineer',
    ],
  },
];

export const HARDWARE = [
  {
    name: 'Tally Box Standard',
    price: '$299',
    period: 'one-time',
    badge: 'HARDWARE',
    comingSoon: true,
    desc: 'Pre-configured Raspberry Pi encoder. Plug into your ATEM aux HDMI output \u2014 streams live video to your dashboard automatically.',
    specs: [
      'Raspberry Pi 4 (4GB)',
      'HDMI capture input',
      'Pre-installed Tally software',
      'Tailscale VPN + SSH for remote management',
      '3Mbps H.264 monitoring stream',
      'Remote config via Tally dashboard',
    ],
    cta: 'Coming Soon',
    ctaHref: '/signup',
    featured: false,
  },
  {
    name: 'Tally Box Pro',
    price: '$799',
    period: 'one-time',
    badge: 'HARDWARE',
    comingSoon: true,
    desc: 'Intel NUC with Blackmagic capture. Supports HDMI and 3G-SDI \u2014 plugs directly into your ATEM SDI aux output.',
    specs: [
      'Intel NUC mini PC',
      'HDMI + 3G-SDI capture input',
      'Pre-installed Tally software',
      'Tailscale VPN + SSH for remote management',
      '3Mbps H.264 monitoring stream',
      'OBS, ProPresenter, audio console on same machine',
    ],
    cta: 'Coming Soon',
    ctaHref: '/signup',
    featured: true,
  },
];

export const SCROLL_DEVICES = [
  'ATEM', 'OBS', 'vMix', 'Ecamm', 'Companion', 'ProPresenter',
  'Planning Center', 'Slack', 'Telegram',
  'Resolume', 'X32', 'Allen & Heath', 'Yamaha', 'HyperDeck', 'PTZ',
  'Blackmagic', 'Teradek', 'YoloBox', 'Dante',
];

export const NAV_LINKS = [
  { href: '#features', label: 'Features' },
  { href: '#the-app', label: 'The App' },
  { href: '#pricing', label: 'Pricing' },
  { href: '/blog', label: 'Blog' },
  { href: '/signin', label: 'Sign In' },
];
