/* ─── Landing page data ─── */

export const FEATURES = [
  { tag: 'SIGNAL FAILOVER', name: 'Signal Lost — Tally Switches Instantly',   desc: 'Multi-signal diagnosis detects video loss, audio silence, and ATEM disconnections. Automatically switches to a safe source, alerts your TD, and verifies stability before switching back.' },
  { tag: 'AUTO-RECOVERY',   name: 'Stream Goes Down — Tally Fixes It',       desc: 'Auto-recovery restarts your stream before the congregation even notices. Works with OBS, vMix, and hardware encoders.' },
  { tag: 'ALERTS',          name: 'Slack + Telegram Alerts',                 desc: 'Your TD gets an alert on Slack or Telegram in seconds — with diagnosis steps and one-tap acknowledge. Escalation if nobody responds in 5 minutes.' },
  { tag: 'PRE-SERVICE',     name: 'Automated System Check',                  desc: 'Green-light confirmation 30 min before every service. Every device tested, every connection verified. No more manual walkthroughs.' },
  { tag: 'REMOTE CONTROL',  name: 'Deep ProPresenter + ATEM Control',        desc: 'Cut cameras, advance slides, trigger looks, send stage messages, start timers — all from your phone or Telegram.' },
  { tag: 'AI COMMANDS',     name: 'Natural Language Control',                desc: 'Type "cut to camera 2 then start recording" and Tally does it. AI-powered command parsing understands plain English — no menus needed.' },
  { tag: 'AUTOPILOT',       name: 'AI Autopilot',                            desc: 'Create step-by-step production rundowns that auto-advance on a timer during service. Up to 25 steps on Enterprise.' },
  { tag: 'CHURCH PORTAL',   name: 'Self-Service Church Portal',              desc: 'Every church gets their own dashboard — manage TDs with viewer, operator, and admin access levels, set service schedules, view session history, configure alerts, and handle billing. TDs log in directly with their own credentials.' },
  { tag: 'TIMELINE',        name: 'Post-Service Debrief',                    desc: 'Every service gets a timeline: what happened, what broke, what auto-recovered. Session recaps push into Planning Center automatically.' },
  { tag: 'PLANNING CENTER', name: 'Planning Center Sync + Write-Back',       desc: 'Pull service times automatically. After each service, production notes push back into the plan — no manual data entry.' },
  { tag: 'GUEST ACCESS',    name: 'Guest TD Tokens',                         desc: 'Generate temporary access tokens for guest TDs or volunteers. Auto-expire in 24 hours. Full audit trail of every action.' },
  { tag: 'ON-CALL',         name: 'On-Call TD Rotation',                     desc: 'Weekly rotation with Telegram swap commands. Alerts route to whoever is on-call — not everyone on the team.' },
  { tag: 'REPORTING',       name: 'Monthly Health Reports',                  desc: 'Uptime stats, incidents, and auto-recoveries per church. Monthly health reports keep leadership in the loop — delivered on the 1st of every month.' },
  { tag: 'AI SETUP',        name: 'AI Setup Assistant',                      desc: 'Upload a patch list or camera plot and Tally auto-configures your mixer channels and ATEM input labels. Parses CSVs, PDFs, and photos using AI vision — setup in minutes, not hours.' },
  { tag: 'MULTI-SITE',      name: 'Built For Multi-Room',                    desc: 'Start with one room on Connect, scale to 3 on Plus, 5 on Pro, or unlimited on Enterprise — without adding chaos to Sunday.' },
  { tag: 'MULTI-ENCODER',   name: 'Any Encoder, Any Workflow',               desc: 'OBS, vMix, Ecamm, Blackmagic, Teradek, YoloBox, Epiphan, AJA HELO — Tally monitors whatever encoder you run.' },
  { tag: 'COMING SOON',     name: 'Live Video Preview',                      desc: 'See your program feed from anywhere. H.264 monitoring stream routed securely — requires a Tally Box hardware encoder. In development.' },
  { tag: 'SETUP GUIDES',    name: '15 Step-by-Step How-To Guides',           desc: 'Plain-language setup guides with Quick Start summaries, difficulty ratings, and collapsible advanced details. Written for volunteers, not engineers.' },
  { tag: 'STREAM GUARD',    name: 'Safety Gates for Live Commands',          desc: 'Tally warns before executing dangerous commands while you\u2019re live \u2014 like stopping a stream or switching sources. Confirms with your TD before anything risky happens.' },
  { tag: 'MIXER CONTROL',   name: 'Full Audio Console Control',              desc: 'EQ, compression, gates, faders, mute/solo \u2014 control every channel on your Allen & Heath, Behringer, Midas, or Yamaha console from Telegram.' },
  { tag: 'PRESET LIBRARY',  name: 'One-Tap Preset Recall',                   desc: 'Save complex multi-device setups and recall them instantly. Mixer scenes, ATEM macros, OBS scene collections \u2014 one tap to switch your entire production config.' },
  { tag: 'MOBILE PORTAL',   name: 'Mobile-Ready Church Portal',              desc: 'Your church dashboard works on any device. Check equipment status, manage TDs, and review sessions from your iPhone during service.' },
  { tag: 'POWER CONTROL',   name: 'Smart Plug Power Cycling',                desc: 'Discover and control Shelly smart plugs on your network. Power-cycle encoders, mixers, or any racked gear remotely — auto-discovered via mDNS with real-time power and voltage monitoring.' },
  { tag: 'ENCODER HEALTH',  name: 'Color-Coded Encoder Metrics',             desc: 'CPU usage, bitrate, FPS, and stream health at a glance with green/yellow/red thresholds. Covers OBS, vMix, hardware encoders, and CDN platforms — with automatic alerts when metrics cross into warning or critical zones.' },
];

export const INTEGRATIONS = [
  { name: 'ATEM Switcher',       tag: 'SWITCHER'  },
  { name: 'OBS Studio',          tag: 'STREAMING' },
  { name: 'vMix',                tag: 'STREAMING' },
  { name: 'Ecamm Live',          tag: 'STREAMING' },
  { name: 'ProPresenter',        tag: 'SLIDES'    },
  { name: 'Bitfocus Companion',  tag: 'CONTROL'   },
  { name: 'Planning Center',     tag: 'SCHEDULE'  },
  { name: 'Slack',               tag: 'ALERTS'    },
  { name: 'Telegram',            tag: 'ALERTS'    },
  { name: 'Resolume Arena',      tag: 'VIDEO WALL'},
  { name: 'Allen & Heath',       tag: 'AUDIO'     },
  { name: 'Behringer X32',       tag: 'AUDIO'     },
  { name: 'Midas M32',           tag: 'AUDIO'     },
  { name: 'Yamaha CL/QL/TF',      tag: 'AUDIO'     },
  { name: 'HyperDeck',           tag: 'RECORD'    },
  { name: 'PTZ Cameras',         tag: 'CAMERA'    },
  { name: 'Video Hub',           tag: 'ROUTER'    },
  { name: 'Blackmagic Encoder',  tag: 'ENCODER'   },
  { name: 'Teradek',             tag: 'ENCODER'   },
  { name: 'YoloBox',             tag: 'ENCODER'   },
  { name: 'Epiphan',             tag: 'ENCODER'   },
  { name: 'AJA HELO',            tag: 'ENCODER'   },
  { name: 'YouTube Live',        tag: 'CDN'       },
  { name: 'Facebook Live',      tag: 'CDN'       },
  { name: 'Shelly Smart Plugs',  tag: 'POWER'     },
];

export const STEPS = [
  {
    num: '01',
    title: 'Install',
    desc: '10-minute setup. Run the app on your booth computer. Connect to your ATEM, OBS, and Companion by entering their IP addresses. The AI Setup Assistant can auto-configure your mixer and camera labels from a patch list.',
  },
  {
    num: '02',
    title: 'Connect',
    desc: 'Your church appears live on the Tally dashboard. Every device, every status — instantly visible from anywhere.',
  },
  {
    num: '03',
    title: 'Relax',
    desc: 'Tally watches your entire production. If something breaks, it fixes it first — then tells you.',
  },
];

export const PRICING = [
  {
    name: 'Connect',
    plan: 'connect',
    monthlyPrice: 79,
    annualPrice: 711,
    foundingMonthlyPrice: 49,
    foundingAnnualPrice: 441,
    desc: 'Monitoring, alerts, and remote control for a single room.',
    featured: false,
    cta: 'Start Free Trial \u2192',
    ctaHref: '/signup?plan=connect',
    features: [
      '1 room included',
      '3 core integrations (ATEM, OBS, vMix)',
      'Pre-service automated check',
      'Slack + Telegram alerts with escalation',
      'Telegram remote control',
      'Auto-recovery (stream restart)',
      'Post-service incident timeline',
      'Church Portal (self-service dashboard)',
      'Email support',
    ],
  },
  {
    name: 'Plus',
    plan: 'plus',
    monthlyPrice: 99,
    annualPrice: 891,
    desc: 'Full integrations, AI commands, and multi-room support for growing teams.',
    featured: false,
    cta: 'Start Free Trial \u2192',
    ctaHref: '/signup?plan=plus',
    features: [
      'Everything in Connect',
      'Up to 3 rooms',
      'Signal failover (auto-switch to safe source on signal loss)',
      'All 23 device integrations',
      'Deep ProPresenter control (looks, timers, stage messages)',
      'On-call TD rotation',
      'Guest TD access tokens',
      'AI natural language commands',
      'AI Autopilot (5 automation rules)',
      'AI Setup Assistant (auto-configure from patch lists)',
      'Priority email support',
    ],
  },
  {
    name: 'Pro',
    plan: 'pro',
    monthlyPrice: 149,
    annualPrice: 1341,
    desc: 'AI autopilot, Planning Center sync, and monthly reports for multi-room operations.',
    featured: true,
    cta: 'Start Free Trial \u2192',
    ctaHref: '/signup?plan=pro',
    features: [
      'Everything in Plus',
      'Up to 5 rooms',
      'AI Autopilot (10 automation rules)',
      'Planning Center sync + production write-back',
      'Monthly health reports for leadership',
      'Session recaps with full timeline',
      'Priority support',
    ],
  },
  {
    name: 'Enterprise',
    plan: 'managed',
    monthlyPrice: 499,
    annualPrice: 4491,
    desc: 'Unlimited rooms, white-glove onboarding, and dedicated support.',
    featured: false,
    cta: 'Contact Sales \u2192',
    ctaHref: 'mailto:sales@tallyconnect.app',
    features: [
      'Everything in Pro',
      'Unlimited rooms',
      'Dedicated onboarding & configuration',
      'AI Autopilot (25 automation rules)',
      'Custom autopilot rules built for you',
      'Remote configuration changes',
      'Monthly system health review',
      '15-minute response SLA (Mon–Fri 9–5 ET + service windows)',
      'Dedicated support engineer',
    ],
  },
];

export const HARDWARE = [
  {
    name: 'Tally Box Standard',
    price: '$299',
    period: 'one-time',
    badge: 'HARDWARE',
    comingSoon: true,
    desc: 'Pre-configured Raspberry Pi encoder. Plug into your ATEM aux HDMI output \u2014 streams live video to your dashboard automatically.',
    specs: [
      'Raspberry Pi 4 (4GB)',
      'HDMI capture input',
      'Pre-installed Tally software',
      'Tailscale VPN + SSH for remote management',
      '3Mbps H.264 monitoring stream',
      'Remote config via Tally dashboard',
    ],
    cta: 'Coming Soon',
    ctaHref: '/signup',
    featured: false,
  },
  {
    name: 'Tally Box Pro',
    price: '$799',
    period: 'one-time',
    badge: 'HARDWARE',
    comingSoon: true,
    desc: 'Intel NUC with Blackmagic capture. Supports HDMI and 3G-SDI \u2014 plugs directly into your ATEM SDI aux output.',
    specs: [
      'Intel NUC mini PC',
      'HDMI + 3G-SDI capture input',
      'Pre-installed Tally software',
      'Tailscale VPN + SSH for remote management',
      '3Mbps H.264 monitoring stream',
      'OBS, ProPresenter, audio console on same machine',
    ],
    cta: 'Coming Soon',
    ctaHref: '/signup',
    featured: true,
  },
];

export const SCROLL_DEVICES = [
  'ATEM', 'OBS', 'vMix', 'Ecamm', 'Companion', 'ProPresenter',
  'Planning Center', 'Slack', 'Telegram',
  'Resolume', 'X32', 'Allen & Heath', 'Yamaha', 'HyperDeck', 'PTZ',
  'Blackmagic', 'Teradek', 'YoloBox', 'Shelly',
];

export const NAV_LINKS = [
  { href: '#features', label: 'Features' },
  { href: '#the-app', label: 'The App' },
  { href: '#pricing', label: 'Pricing' },
  { href: '/tools/healthcheck/', label: 'Free Tools', children: [
    { href: '/tools/healthcheck/', label: 'Production Health Check' },
    { href: '/tools/checklist/', label: 'Pre-Service Checklist' },
    { href: '/clock', label: 'Broadcast Clock' },
  ]},
  { href: '/blog', label: 'Blog' },
  { href: '/download', label: 'Download' },
  { href: '/church-login', label: 'Sign In' },
];
